# Generated by Django 6.0.6 on 2026-08-09 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Имя родителя')),
                ('parent_breed', models.CharField(max_length=100, verbose_name='Порода родителя')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Титул/Звание')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigrees', to='cats.cat', verbose_name='Кошка')),
            ],
            options={
                'verbose_name': 'Запись родословной',
                'verbose_name_plural': 'Записи родословной',
            },
        ),
    ]
